apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.webui.service.type }} # Default: NodePort  # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: {{ .Values.webui.servicePort }}
      targetPort: {{ .Values.webui.servicePort }}
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000