apiVersion: v2
name: open-webui
description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋"
version: 1.0.0
icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
